version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: taskplanner_db
    environment:
      POSTGRES_USER: taskplanner
      POSTGRES_PASSWORD: taskplanner123
      POSTGRES_DB: taskplanner
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskplanner"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: taskplanner_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy

  # For development, we run the frontend locally.
  # This service is for a production build.
  # frontend:
  #   build: ./frontend
  #   container_name: taskplanner_frontend
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - backend

volumes:
  postgres_data: